

spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "sachin- Developer"
    email: "sachin@eazybank.com"
  onCallSupport:
    - (555) 555-1230
    - (555) 523-1343