services:
    bank-microservice-accounts:
        image: deep0983/accounts:s4
        container_name: accounts-ms
        ports:
            - "8080:8080"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - deep0983-network
#        environment:
#            - "spring.datasource.url=jdbc:mysql://mysql:3306/bank_accounts"


    bank-microservice-loan:
        image: deep0983/loans:s4
        container_name: loans-ms
        ports:
            - "8090:8090"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - deep0983-network

    bank-microservice-cards:
        image: deep0983/cards:s4
        container_name: cards-ms
        ports:
            - "9000:9000"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - deep0983-network

networks:
    deep0983-network:
        driver: "bridge"




